version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: app/docker/Dockerfile
    command: /bin/sh -c "sleep 10 && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TZ=${TIMEZONE}
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGTZ: ${TIMEZONE}
      TZ: ${TIMEZONE}
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data:
