"""make phone numbers unique

Revision ID: 28b73b59f5ff
Revises: faba57883600
Create Date: 2024-08-29 21:08:29.575104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28b73b59f5ff'
down_revision: Union[str, None] = 'faba57883600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('aws_phone_number_id', sa.String(length=255), nullable=False))
    op.create_unique_constraint('PhoneNumbersUnique', 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('PhoneNumbersUnique', 'users', type_='unique')
    op.drop_column('users', 'aws_phone_number_id')
    # ### end Alembic commands ###
