"""Fix alarm job and alarm relationship

Revision ID: 787565ea71f3
Revises: d0709cc3777b
Create Date: 2024-08-29 12:10:54.445460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '787565ea71f3'
down_revision: Union[str, None] = 'd0709cc3777b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('AlarmJobsUnique', 'alarm_jobs', ['alarm_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('AlarmJobsUnique', 'alarm_jobs', type_='unique')
    # ### end Alembic commands ###
