"""remove email fields

Revision ID: faba57883600
Revises: 787565ea71f3
Create Date: 2024-08-29 20:52:30.570620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'faba57883600'
down_revision: Union[str, None] = '787565ea71f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alarm_jobs', 'email_job_id')
    op.drop_column('alarms', 'send_sms')
    op.drop_column('alarms', 'send_email')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('alarms', sa.Column('send_email', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('alarms', sa.Column('send_sms', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('alarm_jobs', sa.Column('email_job_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
